export default {
  user: [],
  admin: "",
  allFoods: [],
  category: [],
  isLogin: false,
  showProduct: false,
  cartItem: [],
  cartLength: 0,
  totalPeice: 0,
  showAlert: false,
  showAlertEditInfo: false,
  showAlertEditPass: false,
  loading: true,
  showLoading: true,
  showSearchLoading: true,
  productObj: {
    name: "",
    category: "",
    price: "",
    type: "",
  },
  allOrder: [],
  userOrder: [],
  showMyOrder: true,
  showOrderDetail: true,
  showThank: true,
};
