export default {
  user: [],
  admin: "",
  allFoods: [],
  category: [],
  isLogin: false,
  showProduct: false,
  cartItem: [],
  totalPeice: 0,
  showAlert: false,
  showAlertEditInfo: false,
  showAlertEditPass: false,
  loading: true,
  showLoading: true,
};
